name: reader
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.9
  flutter_easyrefresh: ^2.1.1
  cupertino_icons: ^0.1.2
  carousel_slider: ^2.1.0
  cached_network_image: ^2.2.0+1
  adsorptionview_flutter: ^0.1.3
  sqflite: ^1.3.0+1
  intl: ^0.16.1
  fluttertoast: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/

